apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-app-secret
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  openai-api-key: {{ .Values.secrets.app.openaiApiKey | b64enc | quote }}