apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-backend-service
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 8000
  type: {{ .Values.backend.service.type | default "ClusterIP" }}