apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-app-dev

bases:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

images:
- name: todo-frontend
  newName: todo-frontend
  newTag: dev
- name: todo-backend
  newName: todo-backend
  newTag: dev

resources:
- ingress-development.yaml