apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-app-prod

bases:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

images:
- name: todo-frontend
  newName: todo-frontend
  newTag: latest
- name: todo-backend
  newName: todo-backend
  newTag: latest

resources:
- ingress-production.yaml