{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-postgres-secret
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.secrets.postgres.db | b64enc | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgres.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | b64enc | quote }}
{{- end }}