{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-postgresql-service
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app: postgresql
  ports:
    - protocol: TCP
      port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
  type: {{ .Values.database.service.type | default "ClusterIP" }}
{{- end }}