apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-frontend-service
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: 3000
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}