apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-app-staging

bases:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

images:
- name: todo-frontend
  newName: todo-frontend
  newTag: staging
- name: todo-backend
  newName: todo-backend
  newTag: staging

resources:
- ingress-staging.yaml